'use strict'; // code generated by pbf v3.2.1

// HistoryData ========================================

var HistoryData = exports.HistoryData = {};

HistoryData.read = function (pbf, end) {
    return pbf.readFields(HistoryData._readField, {lastProcessedDay: 0, map: {}}, end);
};
HistoryData._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.lastProcessedDay = pbf.readVarint();
    else if (tag === 2)  { var entry = HistoryData._FieldEntry2.read(pbf, pbf.readVarint() + pbf.pos); obj.map[entry.key] = entry.value; }
};
HistoryData.write = function (obj, pbf) {
    if (obj.lastProcessedDay) pbf.writeVarintField(1, obj.lastProcessedDay);
    if (obj.map) for (var i in obj.map) if (Object.prototype.hasOwnProperty.call(obj.map, i)) pbf.writeMessage(2, HistoryData._FieldEntry2.write, { key: i, value: obj.map[i] });
};

// HistoryData._FieldEntry2 ========================================

HistoryData._FieldEntry2 = {};

HistoryData._FieldEntry2.read = function (pbf, end) {
    return pbf.readFields(HistoryData._FieldEntry2._readField, {key: "", value: null}, end);
};
HistoryData._FieldEntry2._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.key = pbf.readString();
    else if (tag === 2) obj.value = HistoryRecordArray.read(pbf, pbf.readVarint() + pbf.pos);
};
HistoryData._FieldEntry2.write = function (obj, pbf) {
    if (obj.key) pbf.writeStringField(1, obj.key);
    if (obj.value) pbf.writeMessage(2, HistoryRecordArray.write, obj.value);
};

// HistoryRecordArray ========================================

var HistoryRecordArray = exports.HistoryRecordArray = {};

HistoryRecordArray.read = function (pbf, end) {
    return pbf.readFields(HistoryRecordArray._readField, {records: []}, end);
};
HistoryRecordArray._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.records.push(HistoryRecord.read(pbf, pbf.readVarint() + pbf.pos));
};
HistoryRecordArray.write = function (obj, pbf) {
    if (obj.records) for (var i = 0; i < obj.records.length; i++) pbf.writeMessage(1, HistoryRecord.write, obj.records[i]);
};

// HistoryRecord ========================================

var HistoryRecord = exports.HistoryRecord = {};

HistoryRecord.read = function (pbf, end) {
    return pbf.readFields(HistoryRecord._readField, {date_debut: 0, traitement_date_debut: 0, traitement_date_fin: 0}, end);
};
HistoryRecord._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.date_debut = pbf.readVarint();
    else if (tag === 2) obj.traitement_date_debut = pbf.readVarint();
    else if (tag === 3) obj.traitement_date_fin = pbf.readVarint();
};
HistoryRecord.write = function (obj, pbf) {
    if (obj.date_debut) pbf.writeVarintField(1, obj.date_debut);
    if (obj.traitement_date_debut) pbf.writeVarintField(2, obj.traitement_date_debut);
    if (obj.traitement_date_fin) pbf.writeVarintField(3, obj.traitement_date_fin);
};
